// Code generated by Sharkweb. DO NOT EDIT.

package modules

import (
	"log"

	"github.com/gin-gonic/gin"
	"{{ .ModulePath }}/core/module"
{{- range .Imports }}
	{{ .Alias }} "{{ .Path }}"
{{- end }}
)

func LoadModules() []module.Module {
	return []module.Module{
{{- range .Modules }}
		{{ . }},
{{- end }}
	}
}

func RegisterModules(r *gin.Engine, ctx *module.ModuleContext) {

	api := r.Group("/api")

	for _, m := range LoadModules() {

		log.Println("🔌 Loading module:", m.Name())

		if err := m.Init(ctx); err != nil {
			log.Fatalf("❌ Failed to init module %s: %v", m.Name(), err)
		}

		group := api.Group("/" + m.Name())
		m.RegisterRoutes(group)
	}
}